"""
constants_generated.py — generated from polyris/constants.py by polyris.codegen.sync_enums.

DO NOT EDIT THIS FILE. Run `make generate-enums` (or
`python -m polyris.codegen.sync_enums`) to regenerate.

Canonical source sha (first 16): 091ef2b43f38ed16
"""

class TaskStatus:
    """Task execution status values."""
    WAITING = 'waiting'
    DEPS_READY = 'deps_ready'
    WAITING_DELAY = 'waiting_delay'
    WAITING_PAUSED = 'waiting_paused'
    WAITING_DECISION = 'waiting_decision'
    RUNNING = 'running'
    PENDING = 'pending'
    SUCCESS = 'success'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    UPSTREAM_FAILED = 'upstream_failed'
    ABORTED = 'aborted'
    SKIPPED = 'skipped'
    STOPPED = 'stopped'

TASK_TERMINAL_STATUSES = {
    'aborted',
    'failed',
    'skipped',
    'succeeded',
    'success',
    'upstream_failed',
}
TASK_SUCCESS_STATUSES = {
    'skipped',
    'succeeded',
    'success',
}
TASK_FAILURE_STATUSES = {
    'aborted',
    'failed',
    'upstream_failed',
}
TASK_ACTIVE_STATUSES = {
    'pending',
    'running',
}
TASK_WAITING_STATUSES = {
    'deps_ready',
    'waiting',
    'waiting_decision',
    'waiting_delay',
    'waiting_paused',
}
TASK_STOPPABLE_STATUSES = {
    'deps_ready',
    'pending',
    'running',
    'waiting',
    'waiting_decision',
    'waiting_delay',
    'waiting_paused',
}

class TriggerRule:
    """Airflow-compatible trigger rules."""
    ALL_SUCCESS = 'all_success'
    ALL_FAILED = 'all_failed'
    ALL_DONE = 'all_done'
    ALL_DONE_MIN_ONE_SUCCESS = 'all_done_min_one_success'
    ALL_SKIPPED = 'all_skipped'
    ONE_FAILED = 'one_failed'
    ONE_SUCCESS = 'one_success'
    ONE_DONE = 'one_done'
    NONE_FAILED = 'none_failed'
    NONE_FAILED_MIN_ONE_SUCCESS = 'none_failed_min_one_success'
    NONE_SKIPPED = 'none_skipped'

class PipelineStatus:
    """Aggregate pipeline status — derived from task counts for "today's"
    view in the pipelines sidebar."""
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    RUNNING = 'running'
    WAITING = 'waiting'
    IDLE = 'idle'

class ExecutionStatus:
    """Pipeline-execution status. Canonical lowercase form.

    AWS Step Functions returns these statuses in UPPERCASE; normalize at
    the boundary using `normalize_execution_status` before use.
    """
    RUNNING = 'running'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    TIMED_OUT = 'timed_out'
    ABORTED = 'aborted'
    STOPPED = 'stopped'
    RECOVERED = 'recovered'

class BackfillStatus:
    """Backfill status — aggregate of N partition outcomes (ADR #54)."""
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    PARTIAL = 'partial'
    CANCELED = 'canceled'

class BackfillCascade:
    """Asset backfill cascade mode — how downstream consumers are handled."""
    AUTO = 'auto'
    ALL = 'all'
    NONE = 'none'

class BackfillUpstream:
    """Asset backfill upstream lineage build mode (ADR #92).

    Mirrors BackfillCascade on the upstream side. Codegen-generated into
    constants_generated.py (backend) and ui/src/generated/enums.ts (UI) so the
    backend validator and the TS type derive from this one definition rather
    than hand-maintained copies (ADR #94)."""
    OFF = 'off'
    SMART = 'smart'
    FORCE = 'force'

class BackfillGranularity:
    """Backfill partition cadence (ADR #50)."""
    HOURLY = 'hourly'
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

class StalenessStatus:
    """Asset freshness vs declared SLA window."""
    FRESH = 'fresh'
    WARNING = 'warning'
    STALE = 'stale'
    UNKNOWN = 'unknown'

class AssetOperator:
    """How multiple asset dependencies combine to trigger downstream."""
    AND = 'AND'
    OR = 'OR'

EXECUTION_STATUS_CANONICAL = {
    'aborted',
    'failed',
    'recovered',
    'running',
    'stopped',
    'succeeded',
    'timed_out',
}
BACKFILL_TERMINAL_STATUSES = {
    'canceled',
    'completed',
    'failed',
    'partial',
}
BACKFILL_ACTIVE_STATUSES = {
    'pending',
    'running',
}
BACKFILL_ERROR_CODES = {
    'already_terminal',
    'child_name_too_long',
    'concurrent_backfill_active',
    'granularity_override_not_allowed',
    'id_space_exhausted',
    'internal_error',
    'invalid_downstream',
    'invalid_downstream_for_pipeline_target',
    'invalid_granularity_override',
    'invalid_options',
    'invalid_partition_format',
    'invalid_partition_keys',
    'invalid_partitions',
    'invalid_target',
    'invalid_target_type',
    'invalid_tasks',
    'invalid_upstream',
    'invalid_upstream_for_pipeline_target',
    'malformed_body',
    'malformed_parent',
    'misconfigured',
    'multi_producer_asset',
    'no_producer',
    'not_eligible',
    'not_found',
    'nothing_to_retry',
    'nothing_to_run',
    'partition_keys_not_failed',
    'producer_pipeline_missing',
    'range_too_large',
    'sfn_start_failed',
    'status_race',
    'target_not_found',
    'throttled',
    'unreachable_target_type',
    'upstream_cycle',
}

_EXECUTION_STATUS_UPPERCASE_MAP = {
    'RUNNING': 'running',
    'SUCCEEDED': 'succeeded',
    'FAILED': 'failed',
    'TIMED_OUT': 'timed_out',
    'ABORTED': 'aborted',
    'STOPPED': 'stopped',
    'SUCCESS': 'succeeded',
    'success': 'succeeded',
}

def normalize_execution_status(status, log_warn=None):
    """Normalize a pipeline-execution status to canonical lowercase.

    Generated mirror of polyris.constants.normalize_execution_status.
    See ADR #71 for full reasoning. Idempotent on canonical inputs.
    """
    if status is None:
        return None
    if status in EXECUTION_STATUS_CANONICAL:
        return status
    mapped = _EXECUTION_STATUS_UPPERCASE_MAP.get(status)
    if mapped is not None:
        return mapped
    if log_warn is not None:
        log_warn("Unexpected execution status; cannot normalize",
                 status=status)
    return status
